# permissions for end users to view patchrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: patchwork
    app.kubernetes.io/managed-by: kustomize
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: patchrule-viewer-role
rules:
- apiGroups:
  - patchwork.patchwork.io
  resources:
  - patchrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - patchwork.patchwork.io
  resources:
  - patchrules/status
  verbs:
  - get
