nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/andreasgerner/patchwork
  tag: ""  # defaults to appVersion
  pullPolicy: IfNotPresent

imagePullSecrets: []

replicaCount: 1
revisionHistoryLimit: 3

leaderElect: true

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

terminationGracePeriodSeconds: 10

nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []

serviceAccount:
  create: true
  name: ""
  annotations: {}

metrics:
  enabled: false
  port: 8080
  serviceMonitor:
    enabled: false
    interval: "30s"
    scrapeTimeout: ""
    labels: {}

podDisruptionBudget:
  enabled: true
  maxUnavailable: 1
  # minAvailable: 1  # use either maxUnavailable or minAvailable, not both
