apiVersion: patchwork.io/v1
kind: PatchRule
metadata:
  name: ingress-aws-lb
spec:
  target:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    conditions:
      metadata:
        labels:
          app: sample
  overwrite: true
  additions:
    metadata:
      annotations:
        alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-Res-PQ-2025-09
      labels:
        managed-by: aws-lb-controller
  removals:
    metadata:
      annotations:
        - deprecated-annotation
